sudo: required
services:
  - docker
 
before_install:
  - docker build -t younesamine/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true younesamine/react-test npm test

after_success:
  - docker build -t younesamine/multi-client ./client
  - docker build -t younesamine/multi-nginx ./nginx
  - docker build -t younesamine/multi-server ./server
  - docker build -t younesamine/multi-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push younesamine/multi-client
  - docker push younesamine/multi-nginx
  - docker push younesamine/multi-server
  - docker push younesamine/multi-worker
